"""empty message

Revision ID: fce5cef74c5e
Revises: 02ebd97d531a
Create Date: 2023-05-08 22:54:24.965602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fce5cef74c5e'
down_revision = '02ebd97d531a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=False),
    sa.Column('time_out', sa.DateTime(), nullable=False),
    sa.Column('observations', sa.String(length=200), nullable=True),
    sa.Column('Rooms_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Rooms_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('check_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('time_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('observations', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('Rooms_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Rooms_id'], ['rooms.id'], name='check_in_Rooms_id_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='check_in_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='check_in_pkey')
    )
    op.drop_table('checkin')
    # ### end Alembic commands ###
